baseURL = "http://example.org/"
languageCode = "en-us"
title = "Updating Data"
theme = "learn"
[params]
  themeVariant = "green"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]